import type { Metadata } from 'next'
import {
    ClerkProvider,
} from '@clerk/nextjs'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import AppHeader from '@/components/AppHeader'

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
})

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
})

export const metadata: Metadata = {
    title: 'Clerk Next.js Quickstart',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <ClerkProvider>
            <html lang="en">
            <body className={`${geistSans.variable} ${geistMono.variable} min-h-screen bg-slate-950 text-white antialiased bg-[radial-gradient(circle_at_top,rgba(20,184,166,0.18),transparent_45%),radial-gradient(circle_at_bottom,rgba(16,185,129,0.14),transparent_40%)]`}>
            <AppHeader />
            {children}
            </body>
            </html>
        </ClerkProvider>
    )
}
